/**
 * Codex image worker client — FREE ChatGPT-subscription image generation.
 *
 * Replaces the paid OpenAI Images API. Images are generated by the Codex
 * CLI's built-in `image_gen` tool (model: gpt-image-2) on ChatGPT
 * subscription limits — $0 per image.
 *
 * Why a remote worker: SS Command Center runs on Vercel serverless, where
 * the stateful Codex CLI (it needs ~/.codex/auth.json and a writable
 * generated_images dir) cannot run. Generation therefore lives on the
 * always-on OpenClaw box, which is `codex login`-ed with a ChatGPT
 * subscription, behind a tiny HTTP service:
 *   - service:  systemd unit `codex-image-worker` (127.0.0.1:8791)
 *   - ingress:  https://mcp.salutem.solutions/codex-image/generate (nginx + TLS)
 * See docs/wiki/codex-image-generation.md.
 *
 * Env (set locally + in Vercel prod):
 *   CODEX_IMAGE_WORKER_URL    full URL of the /generate endpoint
 *   CODEX_IMAGE_WORKER_TOKEN  shared bearer secret (matches the box .env)
 *
 * Tests/smoke install `globalThis.__SS_CODEX_IMAGE_STUB__` to return canned
 * PNG bytes with no network call.
 */
import sharp from "sharp";

export interface CodexImageStub {
  (args: { prompt: string; size?: string }): Promise<Buffer>;
}

export interface CodexImageResult {
  /** PNG bytes, or null on failure / when the worker is not configured. */
  png: Buffer | null;
  /** True when neither the worker env nor a stub is set (dev-mock path). */
  not_configured: boolean;
  error?: string;
}

// Codex image_gen with reference images routinely takes ~4 minutes. Keep this
// just under the Vercel route maxDuration (300s) + nginx proxy_read_timeout so a
// slow-but-successful generation isn't aborted client-side (240s clipped a 241s
// run). 290s leaves ~10s for the response to travel back.
// Overridable for LOCAL drivers (no serverless ceiling): the timer covers
// QUEUE WAIT + the run, and the box's serial codex queue can hold a COGS
// analyze batch in front of an image job. Vercel routes keep the 290s default
// (their maxDuration is 300s anyway).
const DEFAULT_TIMEOUT_MS = parseInt(process.env.CODEX_IMAGE_TIMEOUT_MS || "290000", 10);

function parseSize(size?: string): { w: number; h: number } | null {
  if (!size) return null;
  const m = /^(\d+)x(\d+)$/.exec(size.trim());
  if (!m) return null;
  return { w: parseInt(m[1], 10), h: parseInt(m[2], 10) };
}

/**
 * The built-in image_gen tool returns its OWN resolution (≈1254² square)
 * and ignores exact pixel requests, so we normalize to the size the caller
 * asked for. This fixes aspect ratio (A+ wants landscape, main image wants
 * square) and gives downstream dimension checks a predictable size.
 *
 * `fit: cover` = a plain resize when aspect already matches (square→square),
 * a centre-crop when it doesn't — fine because our prompts keep the subject
 * centred. Never throws: a resize failure returns the original bytes rather
 * than losing a successfully generated image.
 */
async function normalize(png: Buffer, size?: string): Promise<Buffer> {
  const dim = parseSize(size);
  if (!dim) return png;
  try {
    return await sharp(png)
      .resize(dim.w, dim.h, { fit: "cover", position: "centre" })
      .png()
      .toBuffer();
  } catch {
    return png;
  }
}

export async function generateImagePngViaCodex(args: {
  prompt: string;
  size?: string;
  timeoutMs?: number;
  /** Base64-encoded PNGs passed to the worker as visual references (product
   *  photo + approved frozen-hero anchors). Requires the box worker to support
   *  reference images (server.js writeRefs path). Ignored if empty. */
  referenceImages?: string[];
  /** Image URLs the worker fetches as references (alternative to base64). */
  referenceUrls?: string[];
}): Promise<CodexImageResult> {
  // Test/smoke stub — bypass network + sharp, return the canned bytes.
  const stub = (globalThis as { __SS_CODEX_IMAGE_STUB__?: CodexImageStub })
    .__SS_CODEX_IMAGE_STUB__;
  if (stub) {
    try {
      const png = await stub({ prompt: args.prompt, size: args.size });
      return { png, not_configured: false };
    } catch (e) {
      return {
        png: null,
        not_configured: false,
        error: e instanceof Error ? e.message : String(e),
      };
    }
  }

  const url = process.env.CODEX_IMAGE_WORKER_URL;
  const token = process.env.CODEX_IMAGE_WORKER_TOKEN;
  if (!url || !token) {
    // Dev without the worker wired up → caller falls back to a placeholder.
    return { png: null, not_configured: true };
  }

  let res: Response;
  try {
    res = await fetch(url, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        prompt: args.prompt,
        size: args.size,
        ...(args.referenceImages && args.referenceImages.length > 0
          ? { reference_images: args.referenceImages }
          : {}),
        ...(args.referenceUrls && args.referenceUrls.length > 0
          ? { reference_urls: args.referenceUrls }
          : {}),
      }),
      signal: AbortSignal.timeout(args.timeoutMs ?? DEFAULT_TIMEOUT_MS),
    });
  } catch (e) {
    return {
      png: null,
      not_configured: false,
      error: `Codex worker request failed: ${e instanceof Error ? e.message : String(e)}`,
    };
  }

  if (!res.ok) {
    let body = "";
    try {
      body = (await res.text()).slice(0, 500);
    } catch {
      /* ignore */
    }
    return {
      png: null,
      not_configured: false,
      error: `Codex worker HTTP ${res.status}: ${body}`,
    };
  }

  let png: Buffer;
  try {
    png = Buffer.from(await res.arrayBuffer());
  } catch (e) {
    return {
      png: null,
      not_configured: false,
      error: `Codex worker response read failed: ${e instanceof Error ? e.message : String(e)}`,
    };
  }
  if (png.length === 0) {
    return { png: null, not_configured: false, error: "Codex worker returned empty body" };
  }

  return { png: await normalize(png, args.size), not_configured: false };
}

// ── VISION (image understanding) via the same subscription worker ────────────
// The FREE ChatGPT-subscription path for READING images (product identification),
// mirroring the generation path above. The worker attaches the base64 images to a
// `codex exec -i` run and returns the model's JSON answer. The /analyze URL is
// DERIVED from CODEX_IMAGE_WORKER_URL (…/generate → …/analyze) so no new env var
// is needed — it works wherever generation already works (local + Vercel prod).
// Returns the parsed JSON object, or null if the worker isn't configured / fails
// (caller then falls back to the paid vision API).
export async function identifyImageViaCodex(
  b64Images: string[],
  prompt: string,
  opts?: { timeoutMs?: number },
): Promise<Record<string, unknown> | null> {
  const genUrl = process.env.CODEX_IMAGE_WORKER_URL;
  const token = process.env.CODEX_IMAGE_WORKER_TOKEN;
  if (!genUrl || !token || !b64Images.length) return null;
  const url = genUrl.replace(/\/generate\/?$/, "/analyze");

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${token}` },
      body: JSON.stringify({ prompt, images: b64Images }),
      signal: AbortSignal.timeout(opts?.timeoutMs ?? 200_000),
    });
    if (!res.ok) return null;
    const j = (await res.json()) as { ok?: boolean; result?: Record<string, unknown> };
    return j?.result ?? null;
  } catch {
    return null;
  }
}

// ── VISION via the Claude Code CLI (SECOND free subscription worker) ──────────
// Same contract as identifyImageViaCodex, but hits the worker's /analyze-claude
// endpoint (Claude Max subscription, $0). Lets the vision layer run TWO parallel
// free lanes (Codex + Claude) for ~2x throughput on big sweeps. URL derived from
// CODEX_IMAGE_WORKER_URL (…/generate → …/analyze-claude), so no new env var.
export async function identifyImageViaClaudeCli(
  b64Images: string[],
  prompt: string,
  opts?: { timeoutMs?: number },
): Promise<Record<string, unknown> | null> {
  const genUrl = process.env.CODEX_IMAGE_WORKER_URL;
  const token = process.env.CODEX_IMAGE_WORKER_TOKEN;
  if (!genUrl || !token || !b64Images.length) return null;
  const url = genUrl.replace(/\/generate\/?$/, "/analyze-claude");
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json", authorization: `Bearer ${token}` },
      body: JSON.stringify({ prompt, images: b64Images }),
      signal: AbortSignal.timeout(opts?.timeoutMs ?? 200_000),
    });
    if (!res.ok) return null;
    const j = (await res.json()) as { ok?: boolean; result?: Record<string, unknown> };
    return j?.result ?? null;
  } catch {
    return null;
  }
}
