/**
 * Phase 2.3 Stage 5 — Main image generation via the Codex image worker.
 *
 * One call = one image. Returns a PERMANENT R2 URL (the worker hands back
 * PNG bytes, which we re-host on R2) plus the prompt that was actually sent
 * (so the pipeline can persist it for audit).
 *
 * PROVIDER: images are generated by the Codex CLI's built-in `image_gen`
 * tool (model gpt-image-2) on a ChatGPT *subscription* — NOT the paid
 * OpenAI Images API. Cost per image is $0; `cost_cents` is therefore always
 * 0 (the field is kept for DB/schema compatibility). See
 * src/lib/image-gen/codex-worker.ts and docs/wiki/codex-image-generation.md.
 *
 * Why we re-host every image to R2:
 *   The listing must point at a stable URL forever, and Vladimir's standing
 *   rule (see r2-image-mirror.ts) is "all production images live on our
 *   infrastructure" so retailer/manufacturer URL rotations can't break
 *   listings retroactively.
 *
 * Dev-mock path: if the Codex worker env (CODEX_IMAGE_WORKER_URL /
 * CODEX_IMAGE_WORKER_TOKEN) is missing AND no stub is registered
 * (`globalThis.__SS_CODEX_IMAGE_STUB__`), we return a deterministic
 * placeholder URL so the rest of the pipeline (compliance gate,
 * persistence, UI) can be exercised without a live worker.
 */

import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { generateImagePngViaCodex } from "@/lib/image-gen/codex-worker";

const DEFAULT_BUCKET = "salutem-bundle-factory";
const PLACEHOLDER = "placeholder";

// Per Amazon's main-image guidelines: 1:1 square, white background,
// product fills ≥85% of frame. The worker normalizes output to this size.
const DEFAULT_SIZE = "1024x1024";

export interface RewriteFeedback {
  /** Logos surfaced by Rule 6 on the prior attempt — used to build a
   *  stronger negative prompt. */
  detected_logos?: string[];
  /** Free-text reason from the prior compliance failure (e.g. "main_image_foreign_logos"). */
  failure_reason?: string;
  /** 1-based attempt number — first retry is `attempt: 2`. */
  attempt: number;
}

export interface ImageGenerationInput {
  /** Required: the prompt produced by image-pipeline's prompt builder. */
  prompt: string;
  /** Subdirectory under `prod/` in R2 — typically
   *  `draft-<id>-<channel>`. Sanitised by the R2 mirror. */
  r2_path_slug: string;
  /** Optional: retry feedback so the cost/log can show why we redrew. */
  retry_context?: RewriteFeedback;
  /** Output size (WIDTHxHEIGHT); default `1024x1024`. The worker normalizes
   *  the generated image to exactly this size. */
  size?: string;
  /** @deprecated Ignored — the subscription image_gen tool selects the
   *  model (gpt-image-2). Kept so existing callers (A+ Factory) still type-check. */
  model?: string;
  /** @deprecated Ignored — subscription path has no quality tiers. */
  quality?: "low" | "medium" | "high" | "auto";
}

export interface ImageGenerationOutput {
  /** Permanent R2 public URL, OR `null` when the call failed. */
  image_url: string | null;
  /** Always 0 — generation runs on the ChatGPT subscription (free). Kept
   *  for DB/schema compatibility (GeneratedContent.image_generation_cost_cents). */
  cost_cents: number;
  /** What we sent to the worker (after retry-context augmentation). Stored
   *  for audit so we can later answer "why did we generate this image?". */
  prompt_used: string;
  /** Set when we used the dev-mock path (worker not configured, no stub). */
  mock_mode: boolean;
  /** Set on error — the rest of the pipeline treats this as fail-CLOSED. */
  error?: string;
}

// ── R2 client (graceful nulls, never throws) ───────────────────────────

let _r2: S3Client | null = null;
function getR2Client(): S3Client | null {
  const stub = (globalThis as { __BUNDLE_FACTORY_R2_STUB__?: S3Client })
    .__BUNDLE_FACTORY_R2_STUB__;
  if (stub) return stub;
  if (_r2) return _r2;
  const accountId = process.env.R2_ACCOUNT_ID;
  const accessKey = process.env.R2_ACCESS_KEY_ID;
  const secret = process.env.R2_SECRET_ACCESS_KEY;
  if (
    !accountId ||
    !accessKey ||
    !secret ||
    accountId === PLACEHOLDER ||
    accessKey === PLACEHOLDER ||
    secret === PLACEHOLDER
  ) {
    return null;
  }
  _r2 = new S3Client({
    region: "auto",
    endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
    credentials: { accessKeyId: accessKey, secretAccessKey: secret },
  });
  return _r2;
}

// ── Public surface ─────────────────────────────────────────────────────

const SLUG_RE = /[^a-zA-Z0-9_-]+/g;
function safeSlug(s: string): string {
  return s.replace(SLUG_RE, "-").replace(/^-+|-+$/g, "").slice(0, 80) || "anon";
}

/** Augment the prompt with retry-aware negative constraints. Visible
 *  for tests so the pipeline doesn't have to round-trip the worker just to
 *  verify the negative-brand list rendering. */
export function buildFinalPrompt(input: ImageGenerationInput): string {
  if (!input.retry_context || input.retry_context.attempt < 2) {
    return input.prompt;
  }
  const logos = input.retry_context.detected_logos ?? [];
  const extras: string[] = [];
  if (logos.length > 0) {
    const banList = logos.map((l) => `"${l}"`).join(", ");
    extras.push(
      `CRITICAL — previous attempt was rejected for showing branded packaging. Do NOT show any of these brand names/logos anywhere in the image: ${banList}. Use entirely generic, unbranded packaging.`,
    );
  } else if (input.retry_context.failure_reason) {
    extras.push(
      `Previous attempt failed compliance review (${input.retry_context.failure_reason}). Show generic, unbranded packaging only.`,
    );
  }
  return [input.prompt, ...extras].join("\n\n");
}

export async function generateMainImage(
  input: ImageGenerationInput,
): Promise<ImageGenerationOutput> {
  const r2 = getR2Client();
  const size = input.size ?? DEFAULT_SIZE;
  const finalPrompt = buildFinalPrompt(input);

  // Generate via the Codex worker (subscription image_gen, $0/image).
  const gen = await generateImagePngViaCodex({ prompt: finalPrompt, size });

  // Dev-mock path — worker not configured and no stub registered.
  if (gen.not_configured) {
    return {
      image_url: mockPlaceholderUrl(input.r2_path_slug),
      cost_cents: 0,
      prompt_used: finalPrompt,
      mock_mode: true,
      error: undefined,
    };
  }

  if (!gen.png) {
    return {
      image_url: null,
      cost_cents: 0,
      prompt_used: finalPrompt,
      mock_mode: false,
      error: gen.error ?? "Codex worker returned no image",
    };
  }

  const imageBytes = gen.png;

  // Upload to R2. If R2 unconfigured, fall back to returning a data URL
  // — useful for local dev where R2 creds aren't set. Production has
  // R2 wired up.
  const r2PublicUrl = process.env.R2_PUBLIC_URL;
  if (!r2 || !r2PublicUrl) {
    return {
      image_url: `data:image/png;base64,${imageBytes.toString("base64")}`,
      cost_cents: 0,
      prompt_used: finalPrompt,
      mock_mode: false,
      error: "R2 not configured — returned data: URL (not for production)",
    };
  }

  const bucket = process.env.R2_BUCKET_NAME || DEFAULT_BUCKET;
  const slug = safeSlug(input.r2_path_slug);
  // Phase 2.3 spec puts generated assets under `prod/` — distinct from
  // the `sec/` prefix used by r2-image-mirror.ts for sourced retailer
  // images. Pipeline appends an attempt suffix so retries don't overwrite
  // a still-pending compliance check on the previous attempt.
  const attemptSuffix =
    input.retry_context && input.retry_context.attempt > 1
      ? `-retry${input.retry_context.attempt}`
      : "";
  const key = `prod/${slug}/main${attemptSuffix}.png`;

  try {
    await r2.send(
      new PutObjectCommand({
        Bucket: bucket,
        Key: key,
        Body: imageBytes,
        ContentType: "image/png",
        CacheControl: "public, max-age=31536000",
      }),
    );
  } catch (e) {
    return {
      image_url: null,
      cost_cents: 0,
      prompt_used: finalPrompt,
      mock_mode: false,
      error: `R2 upload failed: ${e instanceof Error ? e.message : String(e)}`,
    };
  }

  const base = r2PublicUrl.replace(/\/+$/, "");
  return {
    image_url: `${base}/${key}`,
    cost_cents: 0,
    prompt_used: finalPrompt,
    mock_mode: false,
  };
}

/** Deterministic placeholder used in dev when the Codex worker isn't wired
 *  up. Returns a stable URL per slug so re-runs don't break the pipeline. */
function mockPlaceholderUrl(slug: string): string {
  const safe = safeSlug(slug);
  // 1024×1024 grey square from placehold.co — no auth, no rate limit.
  return `https://placehold.co/1024x1024/e5e5e5/666666.png?text=mock+${safe}`;
}
