// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Bundle Factory Phase 1 — orchestrates StoreRegistry,
    // BrandAccount, UPCPool import, MarketplaceRule, and GTINExemption
    // tracking. See prisma/seed.ts.
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
