/**
 * Jackie MCP tools — Account Health.
 *
 * Reads the latest AccountHealthSnapshot per store + AccountAlert rows.
 * Refresh path triggers requestReportsForAllStores + pollOpenJobs (the
 * existing Phase 1 orchestrator). All Amazon-only for now.
 */

import { prisma } from "@/lib/prisma";
import {
  pollOpenJobs,
  requestReportsForAllStores,
} from "@/lib/account-health/report-orchestrator";
import {
  amazonChannelToStoreIndex,
  requireAmazonChannel,
} from "../channels";
import type { JackieTool } from "../registry";

const accountHealthGet: JackieTool = {
  name: "account_health_get",
  description:
    "Latest AccountHealthSnapshot for one Amazon channel — includes AHR (0..1000) + Policy Compliance status + ODR/LSR/VTR/OTDR + per-fulfillment-channel ODR breakdown + accountState.",
  write: false,
  input_schema: {
    type: "object",
    properties: { channel: { type: "string" } },
    required: ["channel"],
    additionalProperties: false,
  },
  handler: async (args) => {
    const channel = requireAmazonChannel(args);
    const storeIndex = amazonChannelToStoreIndex(channel);
    const storeId = `store${storeIndex}`;
    const snapshot = await prisma.accountHealthSnapshot.findFirst({
      where: { storeId },
      orderBy: { createdAt: "desc" },
    });
    if (!snapshot) {
      return { error: "no_snapshot", note: "Run account_health_refresh first." };
    }
    return { storeId, snapshot };
  },
};

const accountHealthRefresh: JackieTool = {
  name: "account_health_refresh",
  description:
    "Kick off a fresh Account Health report cycle: request reports across all 5 Amazon stores (Phase 1), then poll any open jobs (Phase 2). Writes new AccountHealthSnapshot rows. Returns the per-store report state. Walmart not included — separate flow.",
  write: true,
  input_schema: {
    type: "object",
    properties: {
      poll_only: { type: "boolean", default: false, description: "When true, skip requesting new reports and only poll existing in-flight jobs." },
    },
    additionalProperties: false,
  },
  handler: async (args) => {
    const pollOnly = args.poll_only === true;
    const requested = pollOnly ? [] : await requestReportsForAllStores();
    const polled = await pollOpenJobs();
    return {
      requested_phase1: requested,
      polled_phase2: polled,
    };
  },
};

const accountAlertsList: JackieTool = {
  name: "account_alerts_list",
  description:
    "List AccountAlert rows generated by the Account Health pipeline for one channel. Channel optional — when omitted, returns alerts across all 5 Amazon stores.",
  write: false,
  input_schema: {
    type: "object",
    properties: {
      channel: { type: "string", description: "Optional Amazon channel filter" },
      level: { type: "string", description: "CRITICAL | WARNING — optional filter" },
      resolved: { type: "boolean", description: "Filter on resolved flag — omit to return both." },
      limit: { type: "number", default: 50 },
    },
    additionalProperties: false,
  },
  handler: async (args) => {
    const where: Record<string, unknown> = {};
    if (typeof args.channel === "string" && args.channel.startsWith("AMAZON_")) {
      const storeIndex = amazonChannelToStoreIndex(args.channel as Parameters<typeof amazonChannelToStoreIndex>[0]);
      where.storeId = `store${storeIndex}`;
    }
    if (typeof args.level === "string") where.level = args.level;
    if (typeof args.resolved === "boolean") where.resolved = args.resolved;
    const limit = typeof args.limit === "number" ? args.limit : 50;
    const rows = await prisma.accountAlert.findMany({
      where,
      orderBy: { createdAt: "desc" },
      take: Math.min(limit, 200),
    });
    return { count: rows.length, alerts: rows };
  },
};

export const tools: JackieTool[] = [
  accountHealthGet,
  accountHealthRefresh,
  accountAlertsList,
];
