-- CreateTable
CREATE TABLE "AtozzClaim" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "amazonOrderId" TEXT NOT NULL,
    "claimType" TEXT NOT NULL,
    "claimReason" TEXT,
    "amount" REAL,
    "detectedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deadline" TEXT,
    "daysUntilDeadline" INTEGER,
    "gmailMessageId" TEXT,
    "trackingNumber" TEXT,
    "carrier" TEXT,
    "shipDate" TEXT,
    "firstScanDate" TEXT,
    "deliveredDate" TEXT,
    "shippedOnTime" BOOLEAN,
    "claimsProtectedBadge" BOOLEAN,
    "evidenceSummary" TEXT,
    "strategyType" TEXT,
    "strategyConfidence" TEXT,
    "generatedResponse" TEXT,
    "editedResponse" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "amazonDecision" TEXT,
    "decisionDate" TEXT,
    "amountCharged" REAL,
    "amountSaved" REAL,
    "appealSubmitted" BOOLEAN NOT NULL DEFAULT false,
    "appealText" TEXT,
    "appealDecision" TEXT,
    "vladimirNotes" TEXT,
    "csCaseId" TEXT
);
